### ISSUE TITLE
Propagate the version inside popup.html

### ISSUE THREAD

**Issue by lirtistan** [leonvogt/hotwire-dev-tools#45]
Hi,

maybe a god enhancement to propagate the version inside popup.html.

```js
const version = chrome.app.getDetails().version
```

Helps to indentify the version inside issues (Screenshots).

**Comment by lirtistan** [comment]
```js
const version = chrome.runtime.getManifest().version
```

**Comment by lirtistan** [comment]
![Screenshot from 2024-06-13 09-11-30](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/07b630f9-0632-4aa8-81f2-cba3c64b9286)

**Comment by leonvogt** [comment]
Hi @lirtistan, I really like this idea!    
Thanks for suggesting it and already submitting a PR!    

I would probably show the version a little less prominently, since it's mostly interesting for debugging purposes.    
What do you think about moving it to a corner? Maybe something like this:     
![Untitled](https://github.com/leonvogt/hotwire-dev-tools/assets/17851143/5e43d395-0093-425c-9f3c-304840eeeb99)

**Comment by lirtistan** [comment]
ok i put it in the corner then.

**Comment by lirtistan** [comment]
But i keept the font a but larger because i can't assume all devs have good eyes, just to be fair.

![Screenshot from 2024-06-13 21-02-13](https://github.com/leonvogt/hotwire-dev-tools/assets/54737363/5a016623-b30a-4239-a2d7-8d6ca0a73fa9)

**Comment by leonvogt** [comment]
Fair enough, your solution looks great.    
Thank you  @lirtistan!
